/**
 * Template for apiwatch.config.ts — generated by `apiwatch init`.
 * Copy to project root and fill in values.
 */

export default {
  // APIWatch server URL (e.g. https://apiwatch.yourorg.com)
  serverUrl: 'https://apiwatch.example.com',
  // Unique repo identifier (from server or CLI init)
  repoId: 'your-repo-id',
  // API key for authentication (from server or CLI init)
  apiKey: 'your-api-key',
  // Paths to scan for route files (relative to project root)
  scanPaths: ['src', 'lib'],
  // Paths to ignore (gitignore-style)
  ignorePaths: ['**/node_modules/**', '**/dist/**'],
  // Framework: 'express' | 'fastify' | 'nest' | 'auto'
  framework: 'auto',
  // Track outbound HTTP calls for dependency graph
  trackOutbound: true,
};
