/**
 * CLI template for apiwatch.config.ts (string).
 */

export const APIWATCH_CONFIG_TEMPLATE = `/**
 * APIWatch configuration — generated by apiwatch init
 */
export default {
  serverUrl: '{{SERVER_URL}}',
  repoId: '{{REPO_ID}}',
  apiKey: '{{API_KEY}}',
  scanPaths: ['src'],
  ignorePaths: ['**/node_modules/**', '**/dist/**'],
  framework: '{{FRAMEWORK}}',
  trackOutbound: true,
};
`;
